project:
  type: website
  output-dir: ../docs
  render: 
    - index.ipynb


website:
  title: Student Admissions
  navbar:
    background: '#FF5700'
    right:
      - icon: github
        href: https://github.com/ad1589/dsan-5900.github.io
        aria-label: GitHub
  page-footer:
    right: |
      Made with [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
