project:
  type: website
  output-dir: ../docs
  render: 
    - index.ipynb


website:
  title: Student Internship Admissions
  navbar:
    background: '#0e6ba8'
    right:
      - icon: github
        href: https://github.com/ad1589/dsan-5900.github.io
        aria-label: GitHub
  page-footer:
    right: |
      Made with [Quarto](https://quarto.org/)<br>


format:
  html:
    theme: cosmo
    css: ../docs/styles.css
    toc: true
